version: '3'
services:
  app2:
    image: python-app
    ports:
      - 4000:4000
    build: .
    volumes:
      # - /home/aggelostheofilatos/micro/nrv:/nrv
      - /nrv:/nrv
  app5000:
    image: python5000
    ports:
      - 5000:5000
    # build: app.Dockerfile
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - /nrv:/nrv
  send:
    image: python-send
    ports:
      - 3000:3000
      - 465:465
    # build: mydocker.Dockerfile
    build:
      context: .
      dockerfile: mydocker.Dockerfile
    volumes:
      - /nrv:/nrv
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - /nrv:/nrv
  app3:
    image: app3
    ports:
      - 4001:4001
    # build: app3docker.Dockerfile
    build:
      context: .
      dockerfile: app3docker.Dockerfile
    volumes:
      - /nrv:/nrv
